#!/bin/bash
## enables r/w to system paritions
sudo steamos-readonly disable
## adds deck to wheel to make sudo easier
sudo usermod -a -G wheel deck
## setups pacman
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo sh -c "yes | pacman -Syu --overwrite \*"
## reinstalls saved packages.txt from backup script
## reinstalls yay
sudo pacman -S --needed base-devel git fakeroot --overwrite \*
sudo rm -r yay
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
sudo sh -c "yes | yay -Syu --needed - < packages.txt --overwrite \*"
sudo sh -c "yes | pacman -Scc"
## fixes problem with flatpak version of lutris
#sudo cp config.py /usr/lib/python3.10/site-packages/lutris/util/steam/
sudo python -m compileall /usr/lib/python3.10/site-packages/lutris/util/steam/
## copies vncserver service to proper directory
sudo cp vncserver@.service /etc/systemd/system/
